def get_product_list():
    products = [
        "ACQUA NATURALE", "ACQUA FRIZZANTE", "BIRRA", "VINO BIANCO", "VINO ROSSO",
        "COCA COLA", "ARANCIATA", "SUCCHI DI FRUTTA", "LATTE", "YOGURT", 
        "BURRO", "FORMAGGIO", "GRANA", "MOZZARELLA", "RICOTTA", "UOVA",
        "PROSCIUTTO COTTO", "PROSCIUTTO CRUDO", "SALAME", "MORTADELLA",
        "PANE", "FOCACCIA", "PIZZA", "BISCOTTI", "FETTE BISCOTTATE", 
        "MARMELLATA", "MIELE", "CAFFÈ", "ZUCCHERO", "SALE", "PASTA",
        "RISO", "PASSATA POMODORO", "PELATI", "OLIO EVO", "OLIO SEMI", 
        "ACETO", "MAIONESE", "TONNO", "FARINA", "LIEVITO", "MELE", 
        "BANANE", "PERE", "LIMONI", "ARANCE", "INSALATA", "POMODORI", 
        "PATATE", "CAROTE", "CIPOLLE", "AGLIO", "ZUCCHINE", "MELANZANE", 
        "PEPERONI", "POLLO", "BOVINO", "SALSICCIA", "HAMBURGER", "WURSTEL",
        "DETERSIVO PIATTI", "DETERSIVO LAVATRICE", "AMMORBIDENTE", 
        "SGRASSATORE", "CARTA IGIENICA", "CARTA CUCINA", "TOVAGLIOLI",
        "SAPONE", "DENTIFRICIO", "SHAMPOO", "BAGNODOCCIA", "SCHIUMA DA BARBA"
    ]
    # Restituisce la lista in ordine alfabetico e senza doppioni
    return sorted(list(set(products)))
