def get_product_list():
    # Questa è la tua lista reale suddivisa per Categoria e Prodotto
    products = [
        "ACQUE E BIBITE: ACQUA NATURALE", "ACQUE E BIBITE: ACQUA FRIZZANTE", "ACQUE E BIBITE: BIRRA", 
        "ACQUE E BIBITE: VINO BIANCO", "ACQUE E BIBITE: VINO ROSSO", "ACQUE E BIBITE: COCA COLA",
        "LATTICINI: LATTE", "LATTICINI: YOGURT", "LATTICINI: BURRO", "LATTICINI: FORMAGGIO", 
        "LATTICINI: GRANA", "LATTICINI: UOVA",
        "SALUMI: PROSCIUTTO COTTO", "SALUMI: PROSCIUTTO CRUDO", "SALUMI: SALAME",
        "FORNERIA: PANE", "FORNERIA: FOCACCIA", "FORNERIA: BISCOTTI", "FORNERIA: FETTE BISCOTTATE",
        "DISPENSA: CAFFÈ", "DISPENSA: ZUCCHERO", "DISPENSA: SALE", "DISPENSA: PASTA", 
        "DISPENSA: RISO", "DISPENSA: PASSATA POMODORO", "DISPENSA: OLIO EVO", "DISPENSA: TONNO", 
        "DISPENSA: FARINA",
        "ORTOFRUTTA: MELE", "ORTOFRUTTA: BANANE", "ORTOFRUTTA: LIMONI", "ORTOFRUTTA: INSALATA", 
        "ORTOFRUTTA: POMODORI", "ORTOFRUTTA: PATATE", "ORTOFRUTTA: CAROTE", "ORTOFRUTTA: CIPOLLE",
        "MACELLERIA: POLLO", "MACELLERIA: BOVINO", "MACELLERIA: SALSICCIA", "MACELLERIA: HAMBURGER",
        "PULIZIA: DETERSIVO PIATTI", "PULIZIA: DETERSIVO LAVATRICE", "PULIZIA: AMMORBIDENTE",
        "IGIENE: CARTA IGIENICA", "IGIENE: CARTA CUCINA", "IGIENE: SAPONE", "IGIENE: DENTIFRICIO", 
        "IGIENE: SHAMPOO"
    ]
    return sorted(products)
