def get_product_list():
    products = [
        # --- PRIMA PARTE ---
        "ACCESSORI CUCINA: Carta Alluminio", "ACCESSORI CUCINA: Carta Forno", "ACCESSORI CUCINA: Sacchetti Freezer",
        "BEVANDE: Acqua Gassata", "BEVANDE: Acqua Naturale", "BEVANDE: Aranciata", "BEVANDE: Coca Cola",
        "BEVANDE ALCOLICHE: Brachetto", "BEVANDE ALCOLICHE: Grappa", "BEVANDE ALCOLICHE: Spumante Dolce", 
        "BEVANDE ALCOLICHE: Vino Bianco", "BEVANDE ALCOLICHE: Vino Fermo", "BEVANDE ALCOLICHE: Vino Frizzante", "BEVANDE ALCOLICHE: Vino Nero",
        "BRODO: Brodo già Pronto Manzo", "BRODO: Brodo già Pronto Misto", "BRODO: Brodo già Pronto Pollo", "BRODO: Dadi",
        "CARTA: Carta cucina", "CARTA: Carta igienica", "CARTA: Fazzoletti",
        "CIBO E ACCESSORI GATTO: Croccantini", "CIBO E ACCESSORI GATTO: Sabbia",
        "COLAZIONE: Biscotti", "COLAZIONE: Caffè in Capsule", "COLAZIONE: Caffè in Grani", "COLAZIONE: Ciambella", 
        "COLAZIONE: Croassaint", "COLAZIONE: Latte", "COLAZIONE: Pancake", "COLAZIONE: Sfogliatine", "COLAZIONE: Torta",
        "CONDIMENTI: Aceto Balsamico", "CONDIMENTI: Aceto di Vino", "CONDIMENTI: Olio di Oliva", "CONDIMENTI: Olio di Semi di Girasole", 
        "CONDIMENTI: Pepe Misto", "CONDIMENTI: Pepe Nero", "CONDIMENTI: Sale Fino", "CONDIMENTI: Sale Grosso",
        "CONSERVE: Cetriolini", "CONSERVE: Concentrato di Pomodoro", "CONSERVE: Giardiniera", "CONSERVE: Passato di Datterini", 
        "CONSERVE: Passato di Pomodoro", "CONSERVE: Pomodori Pelati", "CONSERVE: Pomodori Secchi", "CONSERVE: Pomodorini Pelati",
        "CONSERVE DI PESCE: Salmone", "CONSERVE DI PESCE: Sardine", "CONSERVE DI PESCE: Sgombro", "CONSERVE DI PESCE: Tonno",
        "DETERSIVI: Anti Calcare", "DETERSIVI: Bagno", "DETERSIVI: Candeggina", "DETERSIVI: Lavastoviglie", 
        "DETERSIVI: Lavatrice", "DETERSIVI: Pavimenti", "DETERSIVI: Piatti",
        "FARINE: Farina 0", "FARINE: Farina 00", "FARINE: Semola",
        "FORMAGGI: Burro", "FORMAGGI: Emmental", "FORMAGGI: Gorgonzola", "FORMAGGI: Mozzarella", "FORMAGGI: Parmigiano", 
        "FORMAGGI: Pecorino", "FORMAGGI: Provola", "FORMAGGI: Ricotta",
        "FRUTTA: Albicocche", "FRUTTA: Arance", "FRUTTA: Banane", "FRUTTA: Castagne", "FRUTTA: Fragole", "FRUTTA: Mandaranci", 
        "FRUTTA: Mandarini", "FRUTTA: Mele", "FRUTTA: Mele Golden", "FRUTTA: Mele Golden Rosate", "FRUTTA: Mirtilli", 
        "FRUTTA: Nespole", "FRUTTA: Pesche", "FRUTTA: Pesche Piatte", "FRUTTA: Peschenoci",
        "FRUTTA SECCA: Arachidi", "FRUTTA SECCA: Noci", "FRUTTA SECCA: Pistacchi",
        "IGIENE: Assorbenti Intimi", "IGIENE: BagnoSchiuma", "IGIENE: Deodorante Donna", "IGIENE: Deodorante Uomo", 
        "IGIENE: Salvaslip", "IGIENE: Sapone Intimo", "IGIENE: Sapone Liquido", "IGIENE: Shampoo",
        "IMPASTI PRONTI: Pasta Filo", "IMPASTI PRONTI: Pasta Frolla Rettangolare", "IMPASTI PRONTI: Pasta Frolla Tonda", 
        "IMPASTI PRONTI: Pasta per Pizza", "IMPASTI PRONTI: Pasta Sfoglia Rettangolare", "IMPASTI PRONTI: Pasta Sfoglia Tonda",
        "KEFIR: Agrumi", "KEFIR: Fragola", "KEFIR: Tropicale",
        "LIEVITI: Lievito di Birra", "LIEVITI: Lievito per Dolci", 
        
        # --- SECONDA PARTE ---
        "LIEVITI: Lievito Secco",
        "MAIALE: Arrosto", "MAIALE: Braciole", "MAIALE: Costolette", "MAIALE: Macinato", "MAIALE: Pancetta", "MAIALE: Salsiccia", "MAIALE: Scaloppine",
        "MANZO: Arrosto", "MANZO: Fettine", "MANZO: Fiorentine", "MANZO: Macinato", "MANZO: Ossobuco", "MANZO: Per Brodo", "MANZO: Roast beef",
        "MARMELLATE: Albicocca", "MARMELLATE: Arancia", "MARMELLATE: Ciliegia", "MARMELLATE: Fragola", "MARMELLATE: Pesca",
        "PANIFICATI: Crackers", "PANIFICATI: Grissini", "PANIFICATI: Pancarrè", "PANIFICATI: Pane Fresco",
        "PASTA: Farfalle", "PASTA: Fusilli", "PASTA: Gobbetti", "PASTA: Maccheroni", "PASTA: Paccheri", "PASTA: Penne", 
        "PASTA: Reginette", "PASTA: Sedanini", "PASTA: Spaghetti n°3", "PASTA: Spaghetti n°5", "PASTA: Spaghetti quadrati", 
        "PASTA: Tagliatelle", "PASTA: Torciglioni", "PASTA: Ziti",
        "PASTA FRESCA: Balanzoni", "PASTA FRESCA: Bigoli", "PASTA FRESCA: Ravioli", "PASTA FRESCA: Tortellini", "PASTA FRESCA: Tortelloni",
        "PESCE FRESCO: Calamari", "PESCE FRESCO: Cozze", "PESCE FRESCO: Gamberoni", "PESCE FRESCO: Polipo", 
        "PESCE FRESCO: Salmone", "PESCE FRESCO: Seppie", "PESCE FRESCO: Sgombri", "PESCE FRESCO: Vongole",
        "POLLO: Ali", "POLLO: Cosce", "POLLO: Intero", "POLLO: Petto", "POLLO: Sovracosce", "POLLO: Uova",
        "SALSE: Bernese", "SALSE: ketchup", "SALSE: Maionese", "SALSE: Salsa Barbecue", "SALSE: Salsa Cocktail",
        "SALUMI: Arrosto", "SALUMI: Mortadella", "SALUMI: Prosciutto Cotto", "SALUMI: Prosciutto Crudo", 
        "SALUMI: Salame Felino", "SALUMI: Salame Milano", "SALUMI: Salame Piccante", "SALUMI: Speck",
        "SCATOLAME: Ceci", "SCATOLAME: Fagioli", "SCATOLAME: Lenticchie", "SCATOLAME: Misto Legumi", "SCATOLAME: Piselli",
        "SURGELATI: Calamari", "SURGELATI: Cipolla", "SURGELATI: Funghi Porcini", "SURGELATI: Gamberoni", 
        "SURGELATI: Melanzane Grigliate", "SURGELATI: Misto Pesce per condimenti Pasta", 
        "SURGELATI: Misto Pesce per condimenti Riso", "SURGELATI: Misto soffritto", "SURGELATI: Patate Stick", 
        "SURGELATI: Pizza", "SURGELATI: Polpo", "SURGELATI: Prezzemolo", "SURGELATI: Seppie", "SURGELATI: Vongole", "SURGELATI: Zucchini Grigliati",
        "VERDURA: Aglio", "VERDURA: Cetrioli", "VERDURA: Cipolla", "VERDURA: Insalata", "VERDURA: Melanzane", 
        "VERDURA: Patate", "VERDURA: Peperoni", "VERDURA: Pomodori", "VERDURA: Zucchine",
        "YOGURT: Agrumi", "YOGURT: Ciliegia", "YOGURT: Fragola", "YOGURT: Frutti di Bosco", "YOGURT: Intero", "YOGURT: Magro",
        "ZUCCHERI: Zucchero di Canna", "ZUCCHERI: Zucchero Semolato", "ZUCCHERI: Zucchero Vanigliato"
    ]
    return products
